---
title: "Oregon Community-Based Care Administrative Turnover Study"
format: 
  html: default
  docx: 
    toc: false
    number-sections: false
    reference-doc: reference-document.docx
editor: source
execute: 
  echo: false
  warning: false
  error: false
always_allow_html: true
---


```{r}
#| label: packages

if (!require("pacman")) 
  install.packages("pacman", repos = "https://cran.rstudio.org")

p_load(
  here, 
  conflicted,
  skimr, 
  janitor, 
  scales, 
  labelled, 
  showtext, 
  RStata, 
  lubridate, 
  tidyverse, 
  haven, 
  readxl
)

options("RStata.StataPath" = "/Applications/Stata/StataSE.app/Contents/MacOS/stata-se")
options("RStata.StataVersion" = 17)

conflict_prefer("filter", "dplyr")
```


```{r}
#| label: prep and save data
#| #| eval: false

## Generate the clean, labelled dataset and save it
## Only runs explicitly

rm(list = ls())

## Load survey data
data.survey <-
  read_dta("data/AdminTurnover_Survey_Data_012721_020221_USE_THIS.dta") |>
  select(
    order012621, firstname, lastname, Finished,
    Q1, Q2, starts_with("Q3_"), Q4, starts_with("Q5_"), starts_with("Q6_"),
    Q7, starts_with("Q8_"), starts_with("Q9_"), Q10a, Q11, Q12, 
    starts_with("Q13_"), Q14, starts_with("Q15_"), Q16, Q17, 
    starts_with("Q18_"), starts_with("Q19_"), starts_with("Q20_"), Q21,
    starts_with("Q22_"), Q23, Q24, Q25, starts_with("Q26_"), resp, CCMU,
    catcap, anymc, county, opendate, medi, rural, nonpro
  ) |>
  select(-ends_with("_TEXT")) |>
  clean_names() |>
  mutate(across(everything(), ~ str_trim(.)),
         across(everything(), ~ tolower(.))) |>
  na_if(-99) |>
  filter(!is.na(finished)) |>
  mutate(
    opendate = as_date(opendate),
    across(starts_with("q3_"), ~ replace(., is.na(.), 0)),
    across(starts_with("q5_"), ~ replace(., is.na(.), 0)),
    across(starts_with("q6_"), ~ replace(., is.na(.), 0)), 
    across(starts_with("q15_"), ~ replace(., is.na(.), 0)), 
    across(starts_with("q22_"), ~ replace(., is.na(.), 0))
  ) |> 
  bind_rows(
    read_dta("data/AdminTurnover_Survey_Data_012721_020221_USE_THIS.dta") |>
      select(
        order012621, firstname, lastname, Finished,
        Q1, Q2, starts_with("Q3_"), Q4, starts_with("Q5_"), starts_with("Q6_"),
        Q7, starts_with("Q8_"), starts_with("Q9_"), Q10a, Q11, Q12, 
        starts_with("Q13_"), Q14, starts_with("Q15_"), Q16, Q17, 
        starts_with("Q18_"), starts_with("Q19_"), starts_with("Q20_"), Q21,
        starts_with("Q22_"), Q23, Q24, Q25, starts_with("Q26_"), resp, CCMU,
        catcap, anymc, county, opendate, medi, rural, nonpro
        ) |>
      select(-ends_with("_TEXT")) |>
      clean_names() |>
      mutate(across(everything(), ~ str_trim(.)),
             across(everything(), ~ tolower(.))) |>
      na_if(-99) |>
      filter(is.na(finished)) |>
      mutate(
        opendate = as_date(opendate)
      )
  ) |> 
  mutate(across(starts_with("q"), ~ as.numeric(.)))

## Admin turnover data
data.adturn <- 
  read_excel(here("data", "AdTurn List 021622.xlsx")) |>
      ## clean up variable names
      clean_names() |> 
      rename_all(tolower) |> 
      ## reformat name strings
      mutate(
        across(everything(), ~str_trim(.)), 
        across(everything(), ~tolower(.))
      ) |> 
      ## remove no_admin_record = 'exclude'
      filter(is.na(no_admin_record)) |> 
  select(ccmu1, firstname, lastname, check1, started, ended_100121)

  
## load Facility turnover data
data.facility <- 
  read_excel(here("data", "CBC Administrator List 01010-062519_032720_021522.xlsx")) |> 
      ## clean up variable names
      clean_names() |> 
      rename_all(tolower) |> 
      ## reformat name strings
      mutate(
        across(everything(), ~str_trim(.)), 
        across(everything(), ~tolower(.))
      ) |> 
      left_join(
        read_excel(here("data", "CBC Administrator List 01010-062519_032720_021522.xlsx")) |> 
          ## clean up variable names
          clean_names() |> 
          rename_all(tolower) |>
          ## reformat name strings
          mutate(
            across(everything(), ~str_trim(.)), 
            across(everything(), ~tolower(.))
          ) |>
          ## calculate the turnover ratio
          group_by(facid) |> 
          summarize(facility_n = n(), 
                  early = min(started)) |> 
          ungroup() |> 
          mutate(start_year = lubridate::year(lubridate::ymd(early)), 
                end_year = 2021, 
                span = end_year - start_year, 
                turnover_ratio = facility_n / span), 
        by = ("facid")
        ) |> 
  select(facid, admfirst, admlast, start_year, end_year, span, turnover_ratio)

data <- data.survey |> 
  left_join(data.adturn, 
            by = c("ccmu" = "ccmu1", 
                   "firstname" = "firstname", 
                   "lastname" = "lastname")
            ) |> 
  left_join(data.facility, 
            by = c("ccmu" = "facid", 
                   "firstname" = "admfirst", 
                   "lastname" = "admlast")
            ) |> 
  distinct() |> 
  rename(id = order012621, 
         fac_opendate = opendate, 
         employee_start = started, 
         employee_left = ended_100121, 
         fac_openyear = start_year, 
         fac_closeyear = end_year) |> 
  mutate(
    quit = case_when(!is.na(employee_left) ~ 1,
                     TRUE ~ 0),
    across(c(anymc, medi, nonpro, finished, resp), ~ as.numeric(.)), 
    catcap = case_when(
      catcap == 0 ~ 1,
      catcap == 1 ~ 2,
      catcap == 2 ~ 3,
      catcap == 3 ~ 4,
      TRUE ~ NA_real_
    ),
    rural = case_when(
      rural == 0 ~ 1, 
      rural == 1 ~ 2, 
      rural == 2 ~ 3, 
      TRUE ~ NA_real_
      ), 
    q3a = case_when(
      q3_1 == 1 & q3_2 == 0 & q3_3 == 0 & q3_5 == 0 & q3_6 == 0 & q3_7 == 0 ~ 1, 
      q3_1 == 0 & q3_2 == 1 & q3_3 == 0 & q3_5 == 0 & q3_6 == 0 & q3_7 == 0 ~ 2, 
      q3_1 == 0 & q3_2 == 0 & q3_3 == 1 & q3_5 == 0 & q3_6 == 0 & q3_7 == 0 ~ 3, 
      q3_1 == 0 & q3_2 == 0 & q3_3 == 0 & q3_5 == 1 & q3_6 == 0 & q3_7 == 0 ~ 4, 
      q3_1 == 0 & q3_2 == 0 & q3_3 == 0 & q3_5 == 0 & q3_6 == 1 & q3_7 == 0 ~ 5, 
      q3_1 == 0 & q3_2 == 0 & q3_3 == 0 & q3_5 == 0 & q3_6 == 0 & q3_7 == 1 ~ 6, 
      q3_1 == 0 & q3_2 == 0 & q3_3 == 0 & q3_5 == 0 & q3_6 == 0 & q3_7 == 0 ~ NA_real_,
      TRUE ~ 7
    ), 
    q3b = case_when(
      q3_4 == 1 ~ 1, 
      TRUE ~ 0
    ),
    q7 = case_when(
      q7 == 1 ~ 4, 
      q7 == 2 ~ 3, 
      q7 == 3 ~ 2, 
      q7 == 4 ~ 1, 
      TRUE ~ NA_real_
      ), 
    q10a = case_when(
      q10a == 2 ~ 0, 
      q10a == 1 ~ 1, 
      TRUE ~ NA_real_
      ), 
    q11 = case_when(
      q11 == 20192020 ~ 1, 
      q11 == 2017 ~ 3, 
      TRUE ~ q11
      ), 
    q12 = case_when(
      q12 == 1 ~ 1, 
      q12 == 2 ~ 0, 
      TRUE ~ NA_real_
      ), 
    q13 = case_when(
      q13_1 == 1 & is.na(q13_2) ~ 1, ## Assisted Living
      q13_2 == 1 & is.na(q13_1) ~ 2, ## Memory Care
      q13_1 == 1 & q13_2 == 1 ~ 3, ## Assisted Living and Memory Care
      q13_3 == 1 ~ 4, ## No, first community
      TRUE ~ NA_real_
    ), 
    across(starts_with("q18_"), ~ replace(., . == 2, 0)), 
    across(starts_with("q18_"), ~ replace(., . == 3, NA)), 
    across(starts_with("q19_"), ~ replace(., . == 6, 0)), 
    q21 = case_when(q21 == 2 ~ 0, 
                    TRUE ~ q21),
    q23 = case_when(q23 == 5 ~ 1,
                          q23 == 4 ~ 2,
                          q23 == 3 ~ 3,
                          q23 == 2 ~ 4,
                          q23 == 1 ~ 5,
                          TRUE ~ NA_real_),
    
    q24 = case_when(q24 == 5 ~ 1,
                          q24 == 4 ~ 2,
                          q24 == 3 ~ 3,
                          q24 == 2 ~ 4,
                          q24 == 1 ~ 5,
                          TRUE ~ NA_real_),
    
    q25 = case_when(q25 == 5 ~ 1,
                          q25 == 4 ~ 2,
                          q25 == 3 ~ 3,
                          q25 == 2 ~ 4,
                          q25 == 1 ~ 5,
                          TRUE ~ NA_real_)
  ) |> 
  select(id, firstname, lastname, employee_start, employee_left, quit,
         ccmu, county, fac_opendate, fac_openyear, fac_closeyear, span, 
         turnover_ratio, catcap, anymc, medi, rural, nonpro, 
         quit, finished, resp, q1, q2, q3a, q3b, q4, 
         starts_with("q5_"), starts_with("q6_"), q7, starts_with("q8_"), 
         starts_with("q9_"), q10a, q11, q12, q13,
         everything()
         ) |> 
  select(-q3_1, -q3_2, -q3_3, -q3_4, -q3_5, -q3_6, -q3_7, 
         -q13_1, -q13_2, -q13_3)

## write data
write_csv(data, here("data", "adturn.csv"))

write_dta(data, here("data", "adturn.dta"))

stata("adTurn_label.do", 
      data.out = TRUE) 
```


```{r}
#| label: load data

data <- read_dta(here("data", "adturn.dta"))
```


```{r}
#| label: check subscales

stata(cronbach)
```







